stages:
  - release

release:
  tags:
    - build-shell
  stage: release
  image:
    name: goreleaser/goreleaser
    entrypoint: ['']
  only:
    - tags
  variables:        
    GIT_DEPTH: 0
  script:
    - goreleaser release --clean