project_name: evm-cli
gitlab_urls:
  use_package_registry: true

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      # - arm64
nfpms:
- maintainer: Idan Yael <idanyael@fireblocks.com>
  description: evm utils command line
  homepage: https://gitlab.com/fireblocks/web3/utils/evm-cli
  license: MIT
  formats:
  - deb
  - rpm
  - apk

brews:
  - name: evm-cli
    ids: []    
    goarm: 6    
    goamd64: v1
    url_template: "https://gitlab.com/fireblocks/web3/utils/evm-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    download_strategy: CurlDownloadStrategy
    custom_require: custom_download_strategy

    commit_author:
      name: Idan Yael
      email: idanyael@fireblocks.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    caveats: "How to use this binary"
    homepage: "https://gitlab.com/fireblocks/web3/utils/evm-cli"
    description: "Software to create fast and easy drum rolls."
    license: "MIT"
    skip_upload: false
    repository:      
      owner: idanya
      name: evm-cli
      branch: main      

      pull_request:        
        enabled: true
        draft: true
        base:
          owner: goreleaser
          name: evm-cli
          branch: main

      git:
        url: 'ssh://git@gitlab.com:fireblocks/web3/utils/evm-cli.git'
        private_key: '{{ .Env.DEPLOY_KEY }}'
        ssh_command: 'ssh -i {{ .Env.DEPLOY_KEY }} -o SomeOption=yes'
