project_name: evm-cli
gitlab_urls:
  use_package_registry: true

builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      # - arm64
nfpms:
  - maintainer: Idan Yael <idanyael@fireblocks.com>
    description: evm utils command line
    homepage: https://gitlab.com/fireblocks/web3/utils/evm-cli
    license: MIT
    formats:
    - deb
    - rpm
    - apk

brews:
  - tap:
      owner: "fireblocks/web3/utils"
      name: "evm-cli"
      branch: main
      token: "{{ .Env.GITLAB_TOKEN }}"
    name: evm-cli
    folder: Formula
    commit_author:
      name: Idan Yael
      email: idanyael@fireblocks.com
    goarm: 6
    download_strategy: CurlDownloadStrategy
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    url_template: "https://gitlab.com/fireblocks/web3/utils/evm-cli/releases/{{ .Tag }}/downloads/{{ .ArtifactName }}"                  
    description: "EVM utils command line"
    homepage: "https://gitlab.com/fireblocks/web3/utils/evm-cli"