# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EvmCli < Formula
  desc "EVM utils command line"
  homepage "https://gitlab.com/fireblocks/web3/utils/evm-cli"
  version "1.0.18"

  on_macos do
    url "https://gitlab.com/fireblocks/web3/utils/evm-cli/-/releases/v1.0.18/downloads/evm-cli_1.0.18_darwin_amd64.tar.gz", using: CurlDownloadStrategy
    sha256 "c965acfa9c3944a0af1b1c26d52f5b97f2da2630f799238bfbe2370fcb8533d5"

    def install
      bin.install "evm-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the EvmCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://gitlab.com/fireblocks/web3/utils/evm-cli/-/releases/v1.0.18/downloads/evm-cli_1.0.18_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b50e4902aa050b1a9549e43cf4b2337415477a7e5c53fb670139daa1fbae47f0"

      def install
        bin.install "evm-cli"
      end
    end
  end
end
