# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EvmCli < Formula
  desc "EVM utils command line"
  homepage "https://gitlab.com/fireblocks/web3/utils/evm-cli"
  version "1.0.16"

  on_macos do
    url "https://gitlab.com/fireblocks/web3/utils/evm-cli/releases/download/v1.0.16/evm-cli_1.0.16_darwin_amd64.tar.gz", using: CurlDownloadStrategy
    sha256 "66e79dc1667d08510d7a4c34494f73f00ab0d43833548e8de27d80eb7f0eac10"

    def install
      bin.install "evm-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the EvmCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://gitlab.com/fireblocks/web3/utils/evm-cli/releases/download/v1.0.16/evm-cli_1.0.16_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "b4c8266fb099358e30f2583defa57fbf8ac078c3b66e097e038dab072e76308f"

      def install
        bin.install "evm-cli"
      end
    end
  end
end
