# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EvmCli < Formula
  desc "EVM utils command line"
  homepage "https://gitlab.com/fireblocks/web3/utils/evm-cli"
  version "1.0.17"

  on_macos do
    url "https://gitlab.com/fireblocks/web3/utils/evm-cli/releases/v1.0.17/downloads/evm-cli_1.0.17_darwin_amd64.tar.gz", using: CurlDownloadStrategy
    sha256 "e0b48bf6195a9ac3b33f826881da984e1971c86c4388392b7c1872d1d03006d0"

    def install
      bin.install "evm-cli"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the EvmCli
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://gitlab.com/fireblocks/web3/utils/evm-cli/releases/v1.0.17/downloads/evm-cli_1.0.17_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "73bacaf7971384ef6bf3d0b97612785f342c50be46106a1805ad9440ea69c8da"

      def install
        bin.install "evm-cli"
      end
    end
  end
end
